apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-proxy-api.fullname" . }}
  labels:
    {{- include "ocp-proxy-api.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 6443
      targetPort: https
      protocol: TCP
      name: api
    - port: 443
      targetPort: https
      protocol: TCP
      name: ingress
  selector:
    {{- include "ocp-proxy-api.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
